# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Dev\Projets\plotpy\plotpy\tests\gui\test_qtdesigner.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from qtpy import QtWidgets as QW


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(500, 800)
        self.verticalLayout = QW.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
