# Copyright CEA (2018)

# http://www.cea.fr/

# This software is a computer program whose purpose is to provide an
# Automatic GUI generation for easy dataset editing and display with
# Python.

# This software is governed by the CeCILL license under French law and
# abiding by the rules of distribution of free software.  You can  use,
# modify and/ or redistribute the software under the terms of the CeCILL
# license as circulated by CEA, CNRS and INRIA at the following URL
# "http://www.cecill.info".

# As a counterpart to the access to the source code and  rights to copy,
# modify and redistribute granted by the license, users are provided only
# with a limited warranty  and the software's author,  the holder of the
# economic rights,  and the successive licensors  have only  limited
# liability.

# In this respect, the user's attention is drawn to the risks associated
# with loading,  using,  modifying and/or developing or reproducing the
# software by the user in light of its specific status of free software,
# that may mean  that it is complicated to manipulate,  and  that  also
# therefore means  that it is reserved for developers  and  experienced
# professionals having in-depth computer knowledge. Users are therefore
# encouraged to load and test the software's suitability as regards their
# requirements in conditions enabling the security of their systems and/or
# data to be ensured and,  more generally, to use and operate it in the
# same conditions as regards security.

# The fact that you are presently reading this means that you have had
# knowledge of the CeCILL license and that you accept its terms.


"""
Module plotpy.core.config.config
================================

Handle *plotpy.core* module configuration
(options, images and icons)
"""


import os.path as osp

from guidata.config import UserConfig
from guidata.configtools import add_image_module_path, get_translation


def make_title(basename, count):
    """Make item title with *basename* and *count* number"""
    return "{} {}{:d}".format(basename, _("#"), count)


APP_PATH = osp.dirname(__file__)
add_image_module_path("plotpy", "images")
_ = get_translation("plotpy")

DEFAULTS = {
    "arrayeditor": {
        "font/family/nt": ["Consolas", "Courier New"],
        "font/family/posix": "Bitstream Vera Sans Mono",
        "font/family/mac": "Monaco",
        "font/size": 9,
        "font/bold": False,
    },
    "dicteditor": {
        "font/family/nt": ["Consolas", "Courier New"],
        "font/family/posix": "Bitstream Vera Sans Mono",
        "font/family/mac": "Monaco",
        "font/size": 9,
        "font/italic": False,
        "font/bold": False,
    },
    "texteditor": {
        "font/family/nt": ["Consolas", "Courier New"],
        "font/family/posix": "Bitstream Vera Sans Mono",
        "font/family/mac": "Monaco",
        "font/size": 9,
        "font/italic": False,
        "font/bold": False,
    },
    "internal_console": {
        "max_line_count": 300,
        "working_dir_history": 30,
        "working_dir_adjusttocontents": False,
        "wrap": True,
        "calltips": True,
        "codecompletion/size": [300, 100],
        "codecompletion/auto": False,
        "codecompletion/enter_key": True,
        "codecompletion/case_sensitive": True,
        "external_editor/path": "SciTE",
        "external_editor/gotoline": "-goto:",
        "light_background": True,
    },
    "color_schemes": {
        "names": [
            "emacs",
            "idle",
            "monokai",
            "pydev",
            "scintilla",
            "spyder",
            "spyder/dark",
            "zenburn",
            "solarized/light",
            "solarized/dark",
        ],
        "selected": "spyder",
        # ---- Emacs ----
        "emacs/name": "Emacs",
        #      Name            Color     Bold  Italic
        "emacs/background": "#000000",
        "emacs/currentline": "#2b2b43",
        "emacs/currentcell": "#1c1c2d",
        "emacs/occurrence": "#abab67",
        "emacs/ctrlclick": "#0000ff",
        "emacs/sideareas": "#555555",
        "emacs/matched_p": "#009800",
        "emacs/unmatched_p": "#c80000",
        "emacs/normal": ("#ffffff", False, False),
        "emacs/keyword": ("#3c51e8", False, False),
        "emacs/builtin": ("#900090", False, False),
        "emacs/definition": ("#ff8040", True, False),
        "emacs/comment": ("#005100", False, False),
        "emacs/string": ("#00aa00", False, True),
        "emacs/number": ("#800000", False, False),
        "emacs/instance": ("#ffffff", False, True),
        # ---- IDLE ----
        "idle/name": "IDLE",
        #      Name            Color     Bold  Italic
        "idle/background": "#ffffff",
        "idle/currentline": "#f2e6f3",
        "idle/currentcell": "#feefff",
        "idle/occurrence": "#e8f2fe",
        "idle/ctrlclick": "#0000ff",
        "idle/sideareas": "#efefef",
        "idle/matched_p": "#99ff99",
        "idle/unmatched_p": "#ff9999",
        "idle/normal": ("#000000", False, False),
        "idle/keyword": ("#ff7700", True, False),
        "idle/builtin": ("#900090", False, False),
        "idle/definition": ("#0000ff", False, False),
        "idle/comment": ("#dd0000", False, True),
        "idle/string": ("#00aa00", False, False),
        "idle/number": ("#924900", False, False),
        "idle/instance": ("#777777", True, True),
        # ---- Monokai ----
        "monokai/name": "Monokai",
        #      Name              Color     Bold  Italic
        "monokai/background": "#2a2b24",
        "monokai/currentline": "#484848",
        "monokai/currentcell": "#3d3d3d",
        "monokai/occurrence": "#666666",
        "monokai/ctrlclick": "#0000ff",
        "monokai/sideareas": "#2a2b24",
        "monokai/matched_p": "#688060",
        "monokai/unmatched_p": "#bd6e76",
        "monokai/normal": ("#ddddda", False, False),
        "monokai/keyword": ("#f92672", False, False),
        "monokai/builtin": ("#ae81ff", False, False),
        "monokai/definition": ("#a6e22e", False, False),
        "monokai/comment": ("#75715e", False, True),
        "monokai/string": ("#e6db74", False, False),
        "monokai/number": ("#ae81ff", False, False),
        "monokai/instance": ("#ddddda", False, True),
        # ---- Pydev ----
        "pydev/name": "Pydev",
        #      Name            Color     Bold  Italic
        "pydev/background": "#ffffff",
        "pydev/currentline": "#e8f2fe",
        "pydev/currentcell": "#eff8fe",
        "pydev/occurrence": "#ffff99",
        "pydev/ctrlclick": "#0000ff",
        "pydev/sideareas": "#efefef",
        "pydev/matched_p": "#99ff99",
        "pydev/unmatched_p": "#ff99992",
        "pydev/normal": ("#000000", False, False),
        "pydev/keyword": ("#0000ff", False, False),
        "pydev/builtin": ("#900090", False, False),
        "pydev/definition": ("#000000", True, False),
        "pydev/comment": ("#c0c0c0", False, False),
        "pydev/string": ("#00aa00", False, True),
        "pydev/number": ("#800000", False, False),
        "pydev/instance": ("#000000", False, True),
        # ---- Scintilla ----
        "scintilla/name": "Scintilla",
        #         Name             Color     Bold  Italic
        "scintilla/background": "#ffffff",
        "scintilla/currentline": "#e1f0d1",
        "scintilla/currentcell": "#edfcdc",
        "scintilla/occurrence": "#ffff99",
        "scintilla/ctrlclick": "#0000ff",
        "scintilla/sideareas": "#efefef",
        "scintilla/matched_p": "#99ff99",
        "scintilla/unmatched_p": "#ff9999",
        "scintilla/normal": ("#000000", False, False),
        "scintilla/keyword": ("#00007f", True, False),
        "scintilla/builtin": ("#000000", False, False),
        "scintilla/definition": ("#007f7f", True, False),
        "scintilla/comment": ("#007f00", False, False),
        "scintilla/string": ("#7f007f", False, False),
        "scintilla/number": ("#007f7f", False, False),
        "scintilla/instance": ("#000000", False, True),
        # ---- Spyder ----
        "spyder/name": "Spyder",
        #       Name            Color     Bold  Italic
        "spyder/background": "#ffffff",
        "spyder/currentline": "#f7ecf8",
        "spyder/currentcell": "#fdfdde",
        "spyder/occurrence": "#ffff99",
        "spyder/ctrlclick": "#0000ff",
        "spyder/sideareas": "#efefef",
        "spyder/matched_p": "#99ff99",
        "spyder/unmatched_p": "#ff9999",
        "spyder/normal": ("#000000", False, False),
        "spyder/keyword": ("#0000ff", False, False),
        "spyder/builtin": ("#900090", False, False),
        "spyder/definition": ("#000000", True, False),
        "spyder/comment": ("#adadad", False, True),
        "spyder/string": ("#00aa00", False, False),
        "spyder/number": ("#800000", False, False),
        "spyder/instance": ("#924900", False, True),
        # ---- Spyder/Dark ----
        "spyder/dark/name": "Spyder Dark",
        #           Name             Color     Bold  Italic
        "spyder/dark/background": "#131926",
        "spyder/dark/currentline": "#2b2b43",
        "spyder/dark/currentcell": "#31314e",
        "spyder/dark/occurrence": "#abab67",
        "spyder/dark/ctrlclick": "#0000ff",
        "spyder/dark/sideareas": "#282828",
        "spyder/dark/matched_p": "#009800",
        "spyder/dark/unmatched_p": "#c80000",
        "spyder/dark/normal": ("#ffffff", False, False),
        "spyder/dark/keyword": ("#558eff", False, False),
        "spyder/dark/builtin": ("#aa00aa", False, False),
        "spyder/dark/definition": ("#ffffff", True, False),
        "spyder/dark/comment": ("#7f7f7f", False, False),
        "spyder/dark/string": ("#11a642", False, True),
        "spyder/dark/number": ("#c80000", False, False),
        "spyder/dark/instance": ("#be5f00", False, True),
        # ---- Zenburn ----
        "zenburn/name": "Zenburn",
        #        Name            Color     Bold  Italic
        "zenburn/background": "#3f3f3f",
        "zenburn/currentline": "#333333",
        "zenburn/currentcell": "#2c2c2c",
        "zenburn/occurrence": "#7a738f",
        "zenburn/ctrlclick": "#0000ff",
        "zenburn/sideareas": "#3f3f3f",
        "zenburn/matched_p": "#688060",
        "zenburn/unmatched_p": "#bd6e76",
        "zenburn/normal": ("#dcdccc", False, False),
        "zenburn/keyword": ("#dfaf8f", True, False),
        "zenburn/builtin": ("#efef8f", False, False),
        "zenburn/definition": ("#efef8f", False, False),
        "zenburn/comment": ("#7f9f7f", False, True),
        "zenburn/string": ("#cc9393", False, False),
        "zenburn/number": ("#8cd0d3", False, False),
        "zenburn/instance": ("#dcdccc", False, True),
        # ---- Solarized Light ----
        "solarized/light/name": "Solarized Light",
        #        Name            Color     Bold  Italic
        "solarized/light/background": "#fdf6e3",
        "solarized/light/currentline": "#f5efdB",
        "solarized/light/currentcell": "#eee8d5",
        "solarized/light/occurrence": "#839496",
        "solarized/light/ctrlclick": "#d33682",
        "solarized/light/sideareas": "#eee8d5",
        "solarized/light/matched_p": "#586e75",
        "solarized/light/unmatched_p": "#dc322f",
        "solarized/light/normal": ("#657b83", False, False),
        "solarized/light/keyword": ("#859900", False, False),
        "solarized/light/builtin": ("#6c71c4", False, False),
        "solarized/light/definition": ("#268bd2", True, False),
        "solarized/light/comment": ("#93a1a1", False, True),
        "solarized/light/string": ("#2aa198", False, False),
        "solarized/light/number": ("#cb4b16", False, False),
        "solarized/light/instance": ("#b58900", False, True),
        # ---- Solarized Dark ----
        "solarized/dark/name": "Solarized Dark",
        #        Name            Color     Bold  Italic
        "solarized/dark/background": "#002b36",
        "solarized/dark/currentline": "#083f4d",
        "solarized/dark/currentcell": "#073642",
        "solarized/dark/occurrence": "#657b83",
        "solarized/dark/ctrlclick": "#d33682",
        "solarized/dark/sideareas": "#073642",
        "solarized/dark/matched_p": "#93a1a1",
        "solarized/dark/unmatched_p": "#dc322f",
        "solarized/dark/normal": ("#839496", False, False),
        "solarized/dark/keyword": ("#859900", False, False),
        "solarized/dark/builtin": ("#6c71c4", False, False),
        "solarized/dark/definition": ("#268bd2", True, False),
        "solarized/dark/comment": ("#586e75", False, True),
        "solarized/dark/string": ("#2aa198", False, False),
        "solarized/dark/number": ("#cb4b16", False, False),
        "solarized/dark/instance": ("#b58900", False, True),
    },
    "main": {
        "rich_font/italic": False,
        "rich_font/bold": False,
        "cursor/width": 2,
        "completion/size": (300, 180),
        "report_error/remember_me": False,
        "report_error/remember_token": False,
    },
    "shortcuts": {
        # ---- Global ----
        # ---- Editor ----
        # -- In widgets/sourcecode/codeeditor.py,
        "editor/go to new line": "Ctrl+Shift+Return",
        "editor/go to definition": "Ctrl+G",
        "editor/start of line": "Meta+A",
        "editor/end of line": "Meta+E",
        "editor/previous line": "Meta+P",
        "editor/next line": "Meta+N",
        "editor/previous char": "Meta+B",
        "editor/next char": "Meta+F",
        "editor/previous word": "Meta+Left",
        "editor/next word": "Meta+Right",
        "editor/start of document": "Ctrl+Home",
        "editor/end of document": "Ctrl+End",
        "editor/copy": "Ctrl+C",
        "editor/select all": "Ctrl+A",
        # -- In widgets/editor.py
        "editor/go to line": "Ctrl+L",
        "editor/last edit location": "Ctrl+Alt+Shift+Left",
        "editor/previous cursor position": "Ctrl+Alt+Left",
        "editor/next cursor position": "Ctrl+Alt+Right",
        # ---- In widgets/arraybuider.py ----
        "array_builder/enter array inline": "Ctrl+Alt+M",
        "array_builder/enter array table": "Ctrl+M",
        # ---- In widgets/variableexplorer/aarayeditor.py ----
        "variable_explorer/copy": "Ctrl+C",
        # ---- Consoles (in widgets/shell) ----
        "console/inspect current object": "Ctrl+I",
        "console/clear shell": "Ctrl+L",
        "console/clear line": "Shift+Escape",
        # ---- In widgets/arraybuider.py ----
        "array_builder/enter array inline": "Ctrl+Alt+M",
        "array_builder/enter array table": "Ctrl+M",
    },
    "historylog": {"enable": True, "max_entries": 100, "wrap": True, "go_to_eof": True},
    "plot": {
        "selection/distance": 6,
        "antialiasing": False,
        "title/font/size": 12,
        "title/font/bold": False,
        "selected_curve_symbol/marker": "Rect",
        "selected_curve_symbol/edgecolor": "gray",
        "selected_curve_symbol/facecolor": "black",
        "selected_curve_symbol/alpha": 0.3,
        "selected_curve_symbol/size": 7,
        # Default parameters for plot axes
        "axis/title": "",
        "axis/unit": "",
        "axis/color": "black",
        "axis/title_font/size": 8,
        "axis/title_font/family": "default",
        "axis/title_font/bold": False,
        "axis/title_font/italic": False,
        "axis/ticks_font/size": 8,
        "axis/ticks_font/family": "default",
        "axis/ticks_font/bold": False,
        "axis/ticks_font/italic": False,
        # Default parameters for X/Y image axes
        "image_axis/title": "",
        "image_axis/unit": _("pixels"),
        "image_axis/color": "black",
        "image_axis/title_font/size": 8,
        "image_axis/title_font/family": "default",
        "image_axis/title_font/bold": False,
        "image_axis/title_font/italic": False,
        "image_axis/ticks_font/size": 8,
        "image_axis/ticks_font/family": "default",
        "image_axis/ticks_font/bold": False,
        "image_axis/ticks_font/italic": False,
        # Default parameters for color scale
        "color_axis/title": _("Intensity"),
        "color_axis/unit": _("lsb"),
        "color_axis/color": "black",
        "color_axis/title_font/size": 8,
        "color_axis/title_font/family": "default",
        "color_axis/title_font/bold": False,
        "color_axis/title_font/italic": False,
        "color_axis/ticks_font/size": 8,
        "color_axis/ticks_font/family": "default",
        "color_axis/ticks_font/bold": False,
        "color_axis/ticks_font/italic": False,
        "grid/maj_xenabled": True,
        "grid/maj_yenabled": True,
        "grid/maj_line/color": "darkgray",
        "grid/maj_line/width": 1,
        "grid/maj_line/style": "DotLine",
        "grid/min_xenabled": True,
        "grid/min_yenabled": True,
        "grid/min_line/color": "#eaeaea",
        "grid/min_line/width": 1,
        "grid/min_line/style": "DotLine",
        "marker/curve/symbol/marker": "Rect",
        "marker/curve/symbol/edgecolor": "blue",
        "marker/curve/symbol/facecolor": "cyan",
        "marker/curve/symbol/alpha": 0.8,
        "marker/curve/symbol/size": 7,
        "marker/curve/text/font/size": 8,
        "marker/curve/text/font/family": "default",
        "marker/curve/text/font/bold": False,
        "marker/curve/text/font/italic": False,
        "marker/curve/text/textcolor": "black",
        "marker/curve/text/background_color": "#ffffff",
        "marker/curve/text/background_alpha": 0.8,
        "marker/curve/line/style": "SolidLine",
        "marker/curve/line/color": "black",
        "marker/curve/line/width": 0,
        "marker/curve/sel_symbol/marker": "Rect",
        "marker/curve/sel_symbol/edgecolor": "blue",
        "marker/curve/sel_symbol/facecolor": "cyan",
        "marker/curve/sel_symbol/alpha": 0.8,
        "marker/curve/sel_symbol/size": 7,
        "marker/curve/sel_text/font/size": 8,
        "marker/curve/sel_text/font/family": "default",
        "marker/curve/sel_text/font/bold": False,
        "marker/curve/sel_text/font/italic": False,
        "marker/curve/sel_text/textcolor": "black",
        "marker/curve/sel_text/background_color": "#ffffff",
        "marker/curve/sel_text/background_alpha": 0.8,
        "marker/curve/sel_line/style": "SolidLine",
        "marker/curve/sel_line/color": "black",
        "marker/curve/sel_line/width": 0,
        "marker/curve/markerstyle": "NoLine",
        "marker/curve/spacing": 7,
        "marker/cross/symbol/marker": "Cross",
        "marker/cross/symbol/edgecolor": "black",
        "marker/cross/symbol/facecolor": "red",
        "marker/cross/symbol/alpha": 1.0,
        "marker/cross/symbol/size": 8,
        "marker/cross/text/font/family": "default",
        "marker/cross/text/font/size": 8,
        "marker/cross/text/font/bold": False,
        "marker/cross/text/font/italic": False,
        "marker/cross/text/textcolor": "black",
        "marker/cross/text/background_color": "#ffffff",
        "marker/cross/text/background_alpha": 0.8,
        "marker/cross/line/style": "DashLine",
        "marker/cross/line/color": "yellow",
        "marker/cross/line/width": 1,
        "marker/cross/sel_symbol/marker": "Cross",
        "marker/cross/sel_symbol/edgecolor": "black",
        "marker/cross/sel_symbol/facecolor": "red",
        "marker/cross/sel_symbol/alpha": 1.0,
        "marker/cross/sel_symbol/size": 8,
        "marker/cross/sel_text/font/family": "default",
        "marker/cross/sel_text/font/size": 8,
        "marker/cross/sel_text/font/bold": False,
        "marker/cross/sel_text/font/italic": False,
        "marker/cross/sel_text/textcolor": "black",
        "marker/cross/sel_text/background_color": "#ffffff",
        "marker/cross/sel_text/background_alpha": 0.8,
        "marker/cross/sel_line/style": "DashLine",
        "marker/cross/sel_line/color": "yellow",
        "marker/cross/sel_line/width": 1,
        "marker/cross/markerstyle": "Cross",
        "marker/cross/spacing": 7,
        "marker/selectpoint/symbol/marker": "Rect",
        "marker/selectpoint/symbol/edgecolor": "blue",
        "marker/selectpoint/symbol/facecolor": "cyan",
        "marker/selectpoint/symbol/alpha": 0.8,
        "marker/selectpoint/symbol/size": 7,
        "marker/selectpoint/text/font/size": 8,
        "marker/selectpoint/text/font/family": "default",
        "marker/selectpoint/text/font/bold": False,
        "marker/selectpoint/text/font/italic": False,
        "marker/selectpoint/text/textcolor": "black",
        "marker/selectpoint/text/background_color": "#ffffff",
        "marker/selectpoint/text/background_alpha": 0.8,
        "marker/selectpoint/line/style": "SolidLine",
        "marker/selectpoint/line/color": "black",
        "marker/selectpoint/line/width": 0,
        "marker/selectpoint/sel_symbol/marker": "Rect",
        "marker/selectpoint/sel_symbol/edgecolor": "blue",
        "marker/selectpoint/sel_symbol/facecolor": "cyan",
        "marker/selectpoint/sel_symbol/alpha": 0.8,
        "marker/selectpoint/sel_symbol/size": 7,
        "marker/selectpoint/sel_text/font/size": 8,
        "marker/selectpoint/sel_text/font/family": "default",
        "marker/selectpoint/sel_text/font/bold": False,
        "marker/selectpoint/sel_text/font/italic": False,
        "marker/selectpoint/sel_text/textcolor": "black",
        "marker/selectpoint/sel_text/background_color": "#ffffff",
        "marker/selectpoint/sel_text/background_alpha": 0.8,
        "marker/selectpoint/sel_line/style": "SolidLine",
        "marker/selectpoint/sel_line/color": "black",
        "marker/selectpoint/sel_line/width": 0,
        "marker/selectpoint/markerstyle": "NoLine",
        "marker/selectpoint/spacing": 7,
        "marker/cursor/line/style": "SolidLine",
        "marker/cursor/line/color": "#ff9393",
        "marker/cursor/line/width": 1.0,
        "marker/cursor/symbol/marker": "Ellipse",
        "marker/cursor/symbol/size": 7,
        "marker/cursor/symbol/edgecolor": "white",
        "marker/cursor/symbol/facecolor": "#ff9393",
        "marker/cursor/symbol/alpha": 1.0,
        "marker/cursor/text/font/size": 8,
        "marker/cursor/text/font/family": "default",
        "marker/cursor/text/font/bold": False,
        "marker/cursor/text/font/italic": False,
        "marker/cursor/text/textcolor": "#ff9393",
        "marker/cursor/text/background_color": "#ffffff",
        "marker/cursor/text/background_alpha": 0.8,
        "marker/cursor/sel_line/style": "SolidLine",
        "marker/cursor/sel_line/color": "red",
        "marker/cursor/sel_line/width": 2.0,
        "marker/cursor/sel_symbol/marker": "Ellipse",
        "marker/cursor/sel_symbol/size": 9,
        "marker/cursor/sel_symbol/edgecolor": "white",
        "marker/cursor/sel_symbol/facecolor": "red",
        "marker/cursor/sel_symbol/alpha": 0.9,
        "marker/cursor/sel_text/font/size": 8,
        "marker/cursor/sel_text/font/family": "default",
        "marker/cursor/sel_text/font/bold": True,
        "marker/cursor/sel_text/font/italic": False,
        "marker/cursor/sel_text/textcolor": "red",
        "marker/cursor/sel_text/background_color": "#ffffff",
        "marker/cursor/sel_text/background_alpha": 0.8,
        "marker/cursor/markerstyle": "NoLine",
        "marker/cursor/spacing": 7,
        "shape/drag/line/style": "SolidLine",
        "shape/drag/line/color": "#ffff00",
        "shape/drag/line/width": 1,
        "shape/drag/fill/style": "SolidPattern",
        "shape/drag/fill/color": "white",
        "shape/drag/fill/alpha": 0.1,
        "shape/drag/symbol/marker": "Rect",
        "shape/drag/symbol/size": 3,
        "shape/drag/symbol/edgecolor": "#ffff00",
        "shape/drag/symbol/facecolor": "#ffff00",
        "shape/drag/symbol/alpha": 1.0,
        "shape/drag/sel_line/style": "SolidLine",
        "shape/drag/sel_line/color": "#00ff00",
        "shape/drag/sel_line/width": 1,
        "shape/drag/sel_fill/style": "SolidPattern",
        "shape/drag/sel_fill/color": "white",
        "shape/drag/sel_fill/alpha": 0.1,
        "shape/drag/sel_symbol/marker": "Rect",
        "shape/drag/sel_symbol/size": 9,
        "shape/drag/sel_symbol/edgecolor": "#00aa00",
        "shape/drag/sel_symbol/facecolor": "#00ff00",
        "shape/drag/sel_symbol/alpha": 0.7,
        "shape/imageborder/line/style": "NoPen",
        "shape/imageborder/line/color": "gray",
        "shape/imageborder/line/width": 0,
        "shape/imageborder/fill/style": "NoBrush",
        "shape/imageborder/fill/color": "black",
        "shape/imageborder/fill/alpha": 0.0,
        "shape/imageborder/fill/angle": 0.0,
        "shape/imageborder/fill/sx": 1.0,
        "shape/imageborder/fill/sy": 1.0,
        "shape/imageborder/symbol/marker": "NoSymbol",
        "shape/imageborder/symbol/size": 7,
        "shape/imageborder/symbol/edgecolor": "gray",
        "shape/imageborder/symbol/facecolor": "black",
        "shape/imageborder/symbol/alpha": 0.3,
        "shape/imageborder/sel_line/style": "SolidLine",
        "shape/imageborder/sel_line/color": "gray",
        "shape/imageborder/sel_line/width": 3,
        "shape/imageborder/sel_symbol/marker": "Rect",
        "shape/imageborder/sel_symbol/size": 7,
        "shape/imageborder/sel_symbol/edgecolor": "gray",
        "shape/imageborder/sel_symbol/facecolor": "black",
        "shape/imageborder/sel_symbol/alpha": 0.8,
        "shape/imageborder/sel_fill/style": "NoBrush",
        "shape/imageborder/sel_fill/color": "gray",
        "shape/imageborder/sel_fill/alpha": 0.5,
        "shape/imageborder/sel_fill/angle": 0.0,
        "shape/imageborder/sel_fill/sx": 1.0,
        "shape/imageborder/sel_fill/sy": 1.0,
        "shape/imagefilter/line/style": "SolidLine",
        "shape/imagefilter/line/color": "#ffff00",
        "shape/imagefilter/line/width": 1,
        "shape/imagefilter/sel_line/style": "SolidLine",
        "shape/imagefilter/sel_line/color": "#00ffff",
        "shape/imagefilter/sel_line/width": 2,
        "shape/imagefilter/fill/style": "NoBrush",
        "shape/imagefilter/fill/color": "white",
        "shape/imagefilter/fill/alpha": 0.0,
        "shape/imagefilter/sel_fill/style": "SolidPattern",
        "shape/imagefilter/sel_fill/color": "white",
        "shape/imagefilter/sel_fill/alpha": 0.2,
        "shape/imagefilter/symbol/marker": "Rect",
        "shape/imagefilter/symbol/size": 3,
        "shape/imagefilter/symbol/edgecolor": "#ffff00",
        "shape/imagefilter/symbol/facecolor": "#ffff00",
        "shape/imagefilter/symbol/alpha": 1.0,
        "shape/imagefilter/sel_symbol/marker": "Ellipse",
        "shape/imagefilter/sel_symbol/size": 7,
        "shape/imagefilter/sel_symbol/edgecolor": "#0000ff",
        "shape/imagefilter/sel_symbol/facecolor": "#00ffff",
        "shape/imagefilter/sel_symbol/alpha": 0.8,
        "shape/rectzoom/line/style": "SolidLine",
        "shape/rectzoom/line/color": "#bbbbbb",
        "shape/rectzoom/line/width": 2,
        # not used -- start
        "shape/rectzoom/sel_line/style": "SolidLine",
        "shape/rectzoom/sel_line/color": "green",
        "shape/rectzoom/sel_line/width": 2,
        # not used -- end
        "shape/rectzoom/fill/color": "yellow",
        "shape/rectzoom/fill/style": "SolidPattern",
        "shape/rectzoom/fill/alpha": 0.1,
        # not used -- start
        "shape/rectzoom/symbol/marker": "NoSymbol",
        "shape/rectzoom/symbol/size": 0,
        "shape/rectzoom/symbol/edgecolor": "black",
        "shape/rectzoom/symbol/facecolor": "yellow",
        "shape/rectzoom/symbol/alpha": 1.0,
        "shape/rectzoom/sel_symbol/marker": "Rect",
        "shape/rectzoom/sel_symbol/size": 5,
        "shape/rectzoom/sel_symbol/edgecolor": "black",
        "shape/rectzoom/sel_symbol/facecolor": "yellow",
        "shape/rectzoom/sel_symbol/alpha": 1.0,
        # not used -- end
        "shape/axes/border/line/style": "SolidLine",
        "shape/axes/border/line/color": "magenta",
        "shape/axes/border/line/width": 1,
        "shape/axes/border/sel_line/style": "SolidLine",
        "shape/axes/border/sel_line/color": "magenta",
        "shape/axes/border/sel_line/width": 2,
        "shape/axes/border/fill/style": "NoBrush",
        "shape/axes/border/fill/color": "magenta",
        "shape/axes/border/fill/alpha": 0.0,
        "shape/axes/border/sel_fill/style": "SolidPattern",
        "shape/axes/border/sel_fill/color": "magenta",
        "shape/axes/border/sel_fill/alpha": 0.3,
        "shape/axes/border/symbol/marker": "NoSymbol",
        "shape/axes/border/symbol/size": 0,
        "shape/axes/border/symbol/edgecolor": "black",
        "shape/axes/border/symbol/facecolor": "yellow",
        "shape/axes/border/symbol/alpha": 1.0,
        "shape/axes/border/sel_symbol/marker": "NoSymbol",
        "shape/axes/border/sel_symbol/size": 5,
        "shape/axes/border/sel_symbol/edgecolor": "black",
        "shape/axes/border/sel_symbol/facecolor": "yellow",
        "shape/axes/border/sel_symbol/alpha": 1.0,
        "shape/axes/arrow_size": 8,
        "shape/axes/arrow_angle": 30,
        "shape/axes/xarrow_pen/style": "SolidLine",
        "shape/axes/xarrow_pen/color": "red",
        "shape/axes/xarrow_pen/width": 1,
        "shape/axes/xarrow_brush/color": "red",
        "shape/axes/xarrow_brush/alpha": 0.2,
        "shape/axes/yarrow_pen/style": "SolidLine",
        "shape/axes/yarrow_pen/color": "green",
        "shape/axes/yarrow_pen/width": 1,
        "shape/axes/yarrow_brush/color": "green",
        "shape/axes/yarrow_brush/alpha": 0.2,
        "shape/image_stats/line/style": "DashLine",
        "shape/image_stats/line/color": "#ff88dc",
        "shape/image_stats/line/width": 1,
        "shape/image_stats/fill/style": "SolidPattern",
        "shape/image_stats/fill/color": "white",
        "shape/image_stats/fill/alpha": 0.1,
        "shape/image_stats/symbol/marker": "Rect",
        "shape/image_stats/symbol/size": 3,
        "shape/image_stats/symbol/edgecolor": "#ff55dc",
        "shape/image_stats/symbol/facecolor": "#ff88dc",
        "shape/image_stats/symbol/alpha": 0.6,
        "shape/image_stats/sel_line/style": "DashLine",
        "shape/image_stats/sel_line/color": "#ff00dc",
        "shape/image_stats/sel_line/width": 1,
        "shape/image_stats/sel_fill/style": "SolidPattern",
        "shape/image_stats/sel_fill/color": "white",
        "shape/image_stats/sel_fill/alpha": 0.1,
        "shape/image_stats/sel_symbol/marker": "Rect",
        "shape/image_stats/sel_symbol/size": 5,
        "shape/image_stats/sel_symbol/edgecolor": "#ff00dc",
        "shape/image_stats/sel_symbol/facecolor": "#ff88dc",
        "shape/image_stats/sel_symbol/alpha": 0.7,
        "shape/cross_section/line/style": "DotLine",
        "shape/cross_section/line/color": "#ff5555",
        "shape/cross_section/line/width": 1,
        "shape/cross_section/fill/style": "SolidPattern",
        "shape/cross_section/fill/color": "white",
        "shape/cross_section/fill/alpha": 0.1,
        "shape/cross_section/symbol/marker": "Cross",
        "shape/cross_section/symbol/size": 100,
        "shape/cross_section/symbol/edgecolor": "cyan",
        "shape/cross_section/symbol/facecolor": "cyan",
        "shape/cross_section/symbol/alpha": 0.6,
        "shape/cross_section/sel_line/style": "DotLine",
        "shape/cross_section/sel_line/color": "#ff0000",
        "shape/cross_section/sel_line/width": 1,
        "shape/cross_section/sel_fill/style": "SolidPattern",
        "shape/cross_section/sel_fill/color": "white",
        "shape/cross_section/sel_fill/alpha": 0.1,
        "shape/cross_section/sel_symbol/marker": "Cross",
        "shape/cross_section/sel_symbol/size": 10000,
        "shape/cross_section/sel_symbol/edgecolor": "cyan",
        "shape/cross_section/sel_symbol/facecolor": "cyan",
        "shape/cross_section/sel_symbol/alpha": 0.7,
        "shape/average_cross_section/line/style": "DotLine",
        "shape/average_cross_section/line/color": "#ff5555",
        "shape/average_cross_section/line/width": 1,
        "shape/average_cross_section/fill/style": "SolidPattern",
        "shape/average_cross_section/fill/color": "white",
        "shape/average_cross_section/fill/alpha": 0.1,
        "shape/average_cross_section/symbol/marker": "Diamond",
        "shape/average_cross_section/symbol/size": 7,
        "shape/average_cross_section/symbol/edgecolor": "#ff5555",
        "shape/average_cross_section/symbol/facecolor": "#ff5555",
        "shape/average_cross_section/symbol/alpha": 0.6,
        "shape/average_cross_section/sel_line/style": "DotLine",
        "shape/average_cross_section/sel_line/color": "#ff0000",
        "shape/average_cross_section/sel_line/width": 1,
        "shape/average_cross_section/sel_fill/style": "SolidPattern",
        "shape/average_cross_section/sel_fill/color": "white",
        "shape/average_cross_section/sel_fill/alpha": 0.1,
        "shape/average_cross_section/sel_symbol/marker": "Diamond",
        "shape/average_cross_section/sel_symbol/size": 9,
        "shape/average_cross_section/sel_symbol/edgecolor": "#aa0000",
        "shape/average_cross_section/sel_symbol/facecolor": "#ff0000",
        "shape/average_cross_section/sel_symbol/alpha": 0.7,
        "shape/mask/line/style": "DotLine",
        "shape/mask/line/color": "#5555ff",
        "shape/mask/line/width": 1,
        "shape/mask/fill/style": "SolidPattern",
        "shape/mask/fill/color": "white",
        "shape/mask/fill/alpha": 0.1,
        "shape/mask/symbol/marker": "Rect",
        "shape/mask/symbol/size": 7,
        "shape/mask/symbol/edgecolor": "#5555ff",
        "shape/mask/symbol/facecolor": "#5555ff",
        "shape/mask/symbol/alpha": 0.6,
        "shape/mask/sel_line/style": "DotLine",
        "shape/mask/sel_line/color": "#0000ff",
        "shape/mask/sel_line/width": 1,
        "shape/mask/sel_fill/style": "SolidPattern",
        "shape/mask/sel_fill/color": "white",
        "shape/mask/sel_fill/alpha": 0.1,
        "shape/mask/sel_symbol/marker": "Rect",
        "shape/mask/sel_symbol/size": 9,
        "shape/mask/sel_symbol/edgecolor": "#0000aa",
        "shape/mask/sel_symbol/facecolor": "#0000ff",
        "shape/mask/sel_symbol/alpha": 0.7,
        "shape/point/line/style": "SolidLine",
        "shape/point/line/color": "#ffff00",
        "shape/point/line/width": 1,
        "shape/point/sel_line/style": "SolidLine",
        "shape/point/sel_line/color": "#00ff00",
        "shape/point/sel_line/width": 1,
        "shape/point/fill/style": "NoBrush",
        "shape/point/sel_fill/style": "NoBrush",
        "shape/point/symbol/marker": "XCross",
        "shape/point/symbol/size": 9,
        "shape/point/symbol/edgecolor": "#ffff00",
        "shape/point/symbol/facecolor": "#ffff00",
        "shape/point/symbol/alpha": 1.0,
        "shape/point/sel_symbol/marker": "XCross",
        "shape/point/sel_symbol/size": 12,
        "shape/point/sel_symbol/edgecolor": "#00aa00",
        "shape/point/sel_symbol/facecolor": "#00ff00",
        "shape/point/sel_symbol/alpha": 0.7,
        "shape/segment/line/style": "SolidLine",
        "shape/segment/line/color": "#ffff00",
        "shape/segment/line/width": 1,
        "shape/segment/sel_line/style": "SolidLine",
        "shape/segment/sel_line/color": "#00ff00",
        "shape/segment/sel_line/width": 1,
        "shape/segment/fill/style": "NoBrush",
        "shape/segment/sel_fill/style": "NoBrush",
        "shape/segment/symbol/marker": "XCross",
        "shape/segment/symbol/size": 9,
        "shape/segment/symbol/edgecolor": "#ffff00",
        "shape/segment/symbol/facecolor": "#ffff00",
        "shape/segment/symbol/alpha": 1.0,
        "shape/segment/sel_symbol/marker": "XCross",
        "shape/segment/sel_symbol/size": 12,
        "shape/segment/sel_symbol/edgecolor": "#00aa00",
        "shape/segment/sel_symbol/facecolor": "#00ff00",
        "shape/segment/sel_symbol/alpha": 0.7,
        "shape/label/symbol/marker": "NoSymbol",
        "shape/label/symbol/size": 0,
        "shape/label/symbol/edgecolor": "white",
        "shape/label/symbol/facecolor": "white",
        "shape/label/border/style": "SolidLine",
        "shape/label/border/color": "#cbcbcb",
        "shape/label/border/width": 0,
        "shape/label/font/size": 8,
        "shape/label/font/family": "default",
        "shape/label/font/bold": False,
        "shape/label/font/italic": False,
        "shape/label/color": "white",
        "shape/label/bgcolor": "black",
        "shape/label/bgalpha": 0.25,
        "shape/label/abspos": False,
        "shape/label/move_anchor": True,
        "label/symbol/marker": "NoSymbol",
        "label/symbol/size": 0,
        "label/symbol/edgecolor": "white",
        "label/symbol/facecolor": "white",
        "label/border/style": "SolidLine",
        "label/border/color": "#cbcbcb",
        "label/border/width": 1,
        "label/font/size": 9,
        "label/font/family": "default",
        "label/font/bold": False,
        "label/font/italic": False,
        "label/color": "black",
        "label/bgcolor": "white",
        "label/bgalpha": 0.8,
        "label/anchor": "TL",
        "label/xc": 0,
        "label/yc": 0,
        "label/abspos": False,
        "label/absg": "TR",
        "label/xg": 0.0,
        "label/yg": 0.0,
        # info_label: used in builder.make.computation for example
        "info_label/symbol/marker": "NoSymbol",
        "info_label/symbol/size": 0,
        "info_label/symbol/edgecolor": "white",
        "info_label/symbol/facecolor": "white",
        "info_label/border/style": "SolidLine",
        "info_label/border/color": "#cbcbcb",
        "info_label/border/width": 1,
        "info_label/font/size": 9,
        "info_label/font/family": "default",
        "info_label/font/bold": False,
        "info_label/font/italic": False,
        "info_label/color": "black",
        "info_label/bgcolor": "white",
        "info_label/bgalpha": 0.8,
        "info_label/anchor": "TL",
        "info_label/xc": 0,
        "info_label/yc": 0,
        "info_label/abspos": True,
        "info_label/absg": "TR",
        "info_label/xg": 0.0,
        "info_label/yg": 0.0,
        "legend/border/style": "SolidLine",
        "legend/border/color": "#cbcbcb",
        "legend/border/width": 1,
        "legend/font/size": 8,
        "legend/font/family": "default",
        "legend/font/bold": False,
        "legend/font/italic": False,
        "legend/color": "black",
        "legend/bgcolor": "white",
        "legend/bgalpha": 0.8,
        "legend/anchor": "TR",
        "legend/xc": 0,
        "legend/yc": 0,
        "legend/abspos": True,
        "legend/absg": "TR",
        "legend/xg": 0.0,
        "legend/yg": 0.0,
    },
    "histogram": {
        "antialiasing": False,
        "title/font/size": 11,
        "title/font/bold": False,
        "label/font/size": 9,
        "label/font/bold": False,
        "curve/line/style": "NoPen",
        "curve/line/color": "green",
        "curve/line/width": 1,
        "curve/symbol/marker": "NoSymbol",
        "curve/symbol/size": 0,
        "curve/symbol/edgecolor": "white",
        "curve/symbol/facecolor": "black",
        "curve/symbol/alpha": 1.0,
        "curve/shade": 0.85,
        "curve/curvestyle": "Steps",
        "curve/label": "",
        "range/line/style": "SolidLine",
        "range/line/color": "#ff9393",
        "range/line/width": 1,
        "range/sel_line/style": "SolidLine",
        "range/sel_line/color": "red",
        "range/sel_line/width": 2,
        "range/fill": "red",
        "range/shade": 0.15,
        "range/symbol/marker": "Ellipse",
        "range/symbol/size": 7,
        "range/symbol/edgecolor": "white",
        "range/symbol/facecolor": "#ff9393",
        "range/symbol/alpha": 1.0,
        "range/sel_symbol/marker": "Ellipse",
        "range/sel_symbol/size": 9,
        "range/sel_symbol/edgecolor": "white",
        "range/sel_symbol/facecolor": "red",
        "range/sel_symbol/alpha": 0.9,
        "range/multi/color": "#806060",
        # Default parameters for plot axes
        "axis/title": "",
        "axis/color": "black",
        "axis/title_font/size": 7,
        "axis/title_font/family": "default",
        "axis/title_font/bold": False,
        "axis/title_font/italic": False,
        "axis/ticks_font/size": 7,
        "axis/ticks_font/family": "default",
        "axis/ticks_font/bold": False,
        "axis/ticks_font/italic": False,
        "grid/background": "#FFFFFF",
        "grid/maj_xenabled": True,
        "grid/maj_yenabled": True,
        "grid/maj_line/color": "darkgray",
        "grid/maj_line/width": 1,
        "grid/maj_line/style": "DotLine",
        "grid/min_xenabled": True,
        "grid/min_yenabled": False,
        "grid/min_line/color": "#eaeaea",
        "grid/min_line/width": 1,
        "grid/min_line/style": "DotLine",
        "marker/curve/symbol/marker": "Ellipse",
        "marker/curve/symbol/edgecolor": "black",
        "marker/curve/symbol/facecolor": "blue",
        "marker/curve/symbol/alpha": 0.8,
        "marker/curve/symbol/size": 8,
        "marker/curve/text/font/size": 8,
        "marker/curve/text/font/family": "default",
        "marker/curve/text/font/bold": False,
        "marker/curve/text/font/italic": False,
        "marker/curve/text/textcolor": "darkBlue",
        "marker/curve/text/background_color": "blue",
        "marker/curve/text/background_alpha": 0.2,
        "marker/curve/pen/style": "SolidLine",
        "marker/curve/pen/color": "black",
        "marker/curve/pen/width": 0,
        "marker/curve/markerstyle": "NoLine",
        "marker/cross/symbol/marker": "Cross",
        "marker/cross/symbol/edgecolor": "black",
        "marker/cross/symbol/facecolor": "red",
        "marker/cross/symbol/alpha": 1.0,
        "marker/cross/symbol/size": 8,
        "marker/cross/text/font/family": "default",
        "marker/cross/text/font/size": 8,
        "marker/cross/text/font/bold": False,
        "marker/cross/text/font/italic": False,
        "marker/cross/text/textcolor": "darkBlue",
        "marker/cross/text/background_color": "blue",
        "marker/cross/text/background_alpha": 0.2,
        "marker/cross/pen/style": "SolidLine",
        "marker/cross/pen/color": "black",
        "marker/cross/pen/width": 1,
        "marker/cross/markerstyle": "Cross",
    },
    "cross_section": {
        "antialiasing": False,
        "title/font/size": 11,
        "title/font/bold": False,
        "label/font/size": 9,
        "label/font/bold": False,
        "curve/line/style": "SolidLine",
        "curve/line/color": "blue",
        "curve/line/width": 1,
        "curve/symbol/marker": "NoSymbol",
        "curve/symbol/size": 0,
        "curve/symbol/edgecolor": "white",
        "curve/symbol/facecolor": "black",
        "curve/symbol/alpha": 1.0,
        "curve/shade": 0.15,
        "curve/label": "",
        "range/line/style": "SolidLine",
        "range/line/color": "#ff9393",
        "range/line/width": 1,
        "range/sel_line/style": "SolidLine",
        "range/sel_line/color": "red",
        "range/sel_line/width": 2,
        "range/fill": "red",
        "range/shade": 0.15,
        "range/symbol/marker": "NoSymbol",
        "range/symbol/size": 5,
        "range/symbol/edgecolor": "black",
        "range/symbol/facecolor": "yellow",
        "range/symbol/alpha": 1.0,
        "range/sel_symbol/marker": "Ellipse",
        "range/sel_symbol/size": 9,
        "range/sel_symbol/edgecolor": "white",
        "range/sel_symbol/facecolor": "red",
        "range/sel_symbol/alpha": 0.9,
        "range/multi/color": "#806060",
        # Default parameters for plot axes
        "axis/title": "",
        "axis/color": "black",
        "axis/title_font/size": 7,
        "axis/title_font/family": "default",
        "axis/title_font/bold": False,
        "axis/title_font/italic": False,
        "axis/ticks_font/size": 7,
        "axis/ticks_font/family": "default",
        "axis/ticks_font/bold": False,
        "axis/ticks_font/italic": False,
        "grid/background": "#FFFFFF",
        "grid/maj_xenabled": True,
        "grid/maj_yenabled": True,
        "grid/maj_line/color": "darkgray",
        "grid/maj_line/width": 1,
        "grid/maj_line/style": "DotLine",
        "grid/min_xenabled": False,
        "grid/min_yenabled": False,
        "grid/min_line/color": "#eaeaea",
        "grid/min_line/width": 1,
        "grid/min_line/style": "DotLine",
        "marker/curve/symbol/marker": "Ellipse",
        "marker/curve/symbol/edgecolor": "black",
        "marker/curve/symbol/facecolor": "blue",
        "marker/curve/symbol/alpha": 0.8,
        "marker/curve/symbol/size": 8,
        "marker/curve/text/font/size": 8,
        "marker/curve/text/font/family": "default",
        "marker/curve/text/font/bold": False,
        "marker/curve/text/font/italic": False,
        "marker/curve/text/textcolor": "darkBlue",
        "marker/curve/text/background_color": "blue",
        "marker/curve/text/background_alpha": 0.2,
        "marker/curve/pen/style": "SolidLine",
        "marker/curve/pen/color": "black",
        "marker/curve/pen/width": 0,
        "marker/curve/markerstyle": "NoLine",
        "marker/cross/symbol/marker": "Cross",
        "marker/cross/symbol/edgecolor": "black",
        "marker/cross/symbol/facecolor": "red",
        "marker/cross/symbol/alpha": 1.0,
        "marker/cross/symbol/size": 8,
        "marker/cross/text/font/family": "default",
        "marker/cross/text/font/size": 8,
        "marker/cross/text/font/bold": False,
        "marker/cross/text/font/italic": False,
        "marker/cross/text/textcolor": "darkBlue",
        "marker/cross/text/background_color": "blue",
        "marker/cross/text/background_alpha": 0.2,
        "marker/cross/pen/style": "SolidLine",
        "marker/cross/pen/color": "black",
        "marker/cross/pen/width": 1,
        "marker/cross/markerstyle": "Cross",
    },
}

CONF = UserConfig(DEFAULTS)
